services:
  gateway:
    build: 
      context: gateway
    ports:
      - 1000:1000
    environment:
      SECRET: "TXnXRjvodoWrDp4RI5l7LDs6j2AOIgRtW0mj1eEXhFZ70bmgihklCKD7O2UxoWT4"
      BROKERS: "stats_broker:9092"
      USERS_URL: "http://users:3000"
      POSTS_URL: "http://posts:5000"
      STATS_URL: "http://stats:7000"
    depends_on:
      users:
        condition: service_started
      posts:
        condition: service_started
      stats:
        condition: service_started
      stats_broker:
        condition: service_started
  users:
    build: 
      context: users
    ports:
      - 3000:3000
    environment:
      SECRET: "TXnXRjvodoWrDp4RI5l7LDs6j2AOIgRtW0mj1eEXhFZ70bmgihklCKD7O2UxoWT4"
      DATABASE_URL: "postgres://postgres:tKWN094vCiOCtZ7zEWJv@userdb/soa"
      POSTGRES_DB: "soa"
    depends_on:
      userdb:
        condition: service_healthy
        restart: true
  userdb:
    image: postgres:17.4
    restart: always
    environment:
      POSTGRES_PASSWORD: "tKWN094vCiOCtZ7zEWJv"
      POSTGRES_DB: "soa"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d soa -U postgres"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  posts:
    build: 
      context: posts
    ports:
      - 5000:5000
    environment:
      SECRET: "TXnXRjvodoWrDp4RI5l7LDs6j2AOIgRtW0mj1eEXhFZ70bmgihklCKD7O2UxoWT4"
      DATABASE_URL: "postgres://postgres:XOADIqG6MppRZMTb7cZ6QBHYfi2FhOrN@postsdb/soa"
      POSTGRES_DB: "soa"
    depends_on:
      postsdb:
        condition: service_healthy
        restart: true
  postsdb:
    image: postgres:17.4
    restart: always
    environment:
      POSTGRES_PASSWORD: "XOADIqG6MppRZMTb7cZ6QBHYfi2FhOrN"
      POSTGRES_DB: "soa"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d soa -U postgres"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  stats:
    build:
      context: stats
    ports:
      - 7000:7000
    environment:
      SECRET: "TXnXRjvodoWrDp4RI5l7LDs6j2AOIgRtW0mj1eEXhFZ70bmgihklCKD7O2UxoWT4"
      DATABASE_URL: "http://statsdb:8123"
      CLICKHOUSE_USER: "soa"
      CLICKHOUSE_PASSWORD: "NgeFBacODqTUXVKXn6dDhu5NlNsSBJq1"
    depends_on:
      statsdb:
        condition: service_healthy
        restart: true
  statsdb:
    image: clickhouse/clickhouse-server:25.5.1
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    ports:
      - 8123:8123
      - 9000:9000
    restart: always
    environment:
      CLICKHOUSE_USER: "soa"
      CLICKHOUSE_PASSWORD: "NgeFBacODqTUXVKXn6dDhu5NlNsSBJq1"
    volumes:
      - ./statsdb:/etc/clickhouse-server/users.d/
    depends_on:
      stats_broker: 
        condition: service_healthy
        restart: true
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://statsdb:8123/ping || exit 1
      interval: 10s
      timeout: 10s
      retries: 3

  stats_broker:
    image: apache/kafka:4.0.0
    ports:
      - 9092:9092
      - 9997:9997
    environment:
      # Configure listeners for both docker and host communication
      KAFKA_LISTENERS: CONTROLLER://localhost:9091,HOST://0.0.0.0:9092,DOCKER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: HOST://stats_broker:9092,DOCKER://stats_broker:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,DOCKER:PLAINTEXT,HOST:PLAINTEXT
      # Settings required for KRaft mode
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9091

      # Listener to use for broker-to-broker communication
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER

      # Required for a single node cluster
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

      KAFKA_JMX_PORT: 9997
      KAFKA_JMX_HOSTNAME: kafka
    healthcheck:
      test: nc -z localhost 9092 || exit -1
      start_period: 15s
      interval: 5s
      timeout: 10s
      retries: 10
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:v0.7.2
    ports:
      - 8082:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: true
