openapi: 3.0.1
info:
  version: 0.1.0
  title: Gateway
  description: This service distributes requests to other services
paths:
  /user:
    post:
      summary: Register a new user
      description: Register a new user with given information
      operationId: createUser
      requestBody:
        description: User information
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: ivan_ivanov
                password:
                  type: string
                  format: password
                  example: password
                name:
                  type: string
                  example: Ivan
                surname:
                  type: string
                  example: Ivanov
                birthdate:
                  type: string
                  format: date
                  example: 2025-12-31
                status:
                  type: string
                  example: I'm ok
                mail:
                  type: string
                  format: email
                  example: ivan.ivanov@example.com
                phone:
                  type: string
                  example: 81234567890
      responses:
        '200':
          description: Successful operation
        '400':
          description: Wrong format of a parameter
        '403':
          description: User with such username already exists
  /user/{username}:
    get:
      summary: Get user by username
      description: Get user by username
      operationId: getUser
      parameters:
        - name: username
          in: path
          description: The name of the user
          required: true
          schema:
            type: string
      responses:
        '200': 
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '403':
          description: Not enough permissions to read this user data
        '404':
          description: User not found
      security:
        - cookieAuth: []
    put:
      summary: Change user information
      description: Change user information
      operationId: updateUser
      parameters:
        - name: username
          in: path
          description: The name of the user
          required: true
          schema:
            type: string
      requestBody:
        description: Details of the user to be changed
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200': 
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Wrong format of a parameter
        '403':
          description: Not enough permissions to update this user data
      security:
        - cookieAuth: []

  /login:
    get:
      summary: Login as existing user
      description: Login as existing user with login and password
      operationId: login
      parameters:
        - name: username
          in: query
          description: Username of the user
          required: true
          schema:
            type: string
          example: ivan_ivanov
        - name: password
          in: query
          description: Password of the user
          required: true
          schema:
            type: string
          example: password
      responses:
        '200':
          description: Successful operation
          headers:
            Set-Cookie:
              description: Contains session cookie 
              schema: 
                type: string
                example: session=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Iml2YW5faXZhbm92IiwidGltZXN0YW1wIjoxMjM0NTY3ODl9.0TPDykRjLo4o2Px_mBNoiFMlgzXpl5SSibmGjX1yR7g
        '403':
          description: Wrong login or password
  /post:
    post:
      summary: Create a post
      description: Creates a post from given data
      operationId: createPost
      requestBody:
        description: Post information
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: post_name
                description:
                  type: string
                  example: this post is about smth smth
                is_private:
                  type: boolean
                  example: false
      security:
        - cookieAuth: []
      responses:
        '200':
          description: Successful operation
  /post/{post_id}:
    get:
      summary: Get post by id
      description: Get post by id
      operationId: getPostByID
      parameters:
        - name: post_id
          in: path
          description: The id of the post
          required: true
          schema:
            type: integer
      responses:
        '200': 
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
        '404':
          description: Post not found
      security:
        - cookieAuth: []
    put:
      summary: Change post information
      description: Change post information
      operationId: updatePost
      parameters:
        - name: post_id
          in: path
          description: The id of the post
          required: true
          schema:
            type: string
      requestBody:
        description: Details of the post to be changed
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Post'
      responses:
        '200': 
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Wrong format of a parameter
        '403':
          description: Not enough permissions to update this user data
      security:
        - cookieAuth: []
  /post/page/{from}/{limit}:
    get:
      summary: Get paginated posts
      description: Get posts from given id and limit the number of returned posts
      operationId: getPostsPage
      parameters:
        - name: from
          in: path
          description: The id of the starting post
          required: true
          schema:
            type: integer
        - name: limit
          in: path
          description: The number of retunred posts
          required: true
          schema:
            type: integer
      responses:
        '200': 
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
      security:
        - cookieAuth: []
  /view:
    post:
      summary: View a post
      description: Informs the system about a view of a post
      operationID: viewPost
      requestBody:
        description: Information of viewed post
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                post_id:
                  type: integer
                  format: int64
                  example: 3
      security:
        - cookieAuth: []
      responses:
        '200':
          description: Successful operation
        '500':
          description: Submit to kafka failed
  /like:
    post:
      summary: Like a post
      description: Informs the system about a like of a post
      operationID: likePost
      requestBody:
        description: Information of liked post
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                post_id:
                  type: integer
                  format: int64
                  example: 3
      security:
        - cookieAuth: []
      responses:
        '200':
          description: Successful operation
        '500':
          description: Submit to kafka failed
  /comment:
    post:
      summary: Comment a post
      description: Submits a comment of a post
      operationID: commentPost
      requestBody:
        description: Information about the comment
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                post_id:
                  type: integer
                  format: int64
                  example: 3
                comment:
                  type: string
                  example: This post is very good!
      security:
        - cookieAuth: []
      responses:
        '200':
          description: Successful operation
        '500':
          description: Submit to kafka failed
components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: session
  schemas:
    User:
      type: object
      properties:
        name:
          type: string
          example: Ivan
        surname:
          type: string
          example: Ivanov
        birthdate:
          type: string
          format: date
          example: 2025-12-31
        status:
          type: string
          example: I'm ok
        mail:
          type: string
          format: email
          example: ivan.ivanov@example.com
        phone:
          type: string
          example: 81234567890
    Post:
      type: object
      properties:
        post_id:
          type: integer
          format: int64
          example: 3
        name:
          type: string
          example: post_name
        description:
          type: string
          example: This post is about smth smth
        creator_id:
          type: integer
          format: int32
          example: 1234
        creation_time:
          type: string
          format: time
        update_time:
          type: string
          format: time
        is_private:
          type: boolean
          example: false
        tags:
          type: array
          items:
            type: string
